"""Testing if autofenerate of upgarde and downgrade will work.

Revision ID: 043f6463bdd6
Revises: 4fbc98979eba
Create Date: 2023-09-07 19:02:11.951904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043f6463bdd6'
down_revision: Union[str, None] = '4fbc98979eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
